/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CoverLettersRouteImport } from './routes/cover-letters'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TailoringRouteImport } from './routes/tailoring'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as BuilderIdRouteImport } from './routes/builder.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLettersRoute = CoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TailoringRoute = TailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/builder': typeof BuilderRouteWithChildren
  '/cover-letters': typeof CoverLettersRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tailoring': typeof TailoringRoute
  '/templates': typeof TemplatesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/cover-letters': typeof CoverLettersRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tailoring': typeof TailoringRoute
  '/templates': typeof TemplatesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder': typeof BuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/builder': typeof BuilderRouteWithChildren
  '/cover-letters': typeof CoverLettersRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tailoring': typeof TailoringRoute
  '/templates': typeof TemplatesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzer'
    | '/builder'
    | '/cover-letters'
    | '/library'
    | '/profile'
    | '/settings'
    | '/tailoring'
    | '/templates'
    | '/builder/$id'
    | '/builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer'
    | '/cover-letters'
    | '/library'
    | '/profile'
    | '/settings'
    | '/tailoring'
    | '/templates'
    | '/builder/$id'
    | '/builder'
  id:
    | '__root__'
    | '/'
    | '/analyzer'
    | '/builder'
    | '/cover-letters'
    | '/library'
    | '/profile'
    | '/settings'
    | '/tailoring'
    | '/templates'
    | '/builder/$id'
    | '/builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  CoverLettersRoute: typeof CoverLettersRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TailoringRoute: typeof TailoringRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letters': {
      id: '/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof CoverLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailoring': {
      id: '/tailoring'
      path: '/tailoring'
      fullPath: '/tailoring'
      preLoaderRoute: typeof TailoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof BuilderRoute
    }
  }
}

interface BuilderRouteChildren {
  BuilderIdRoute: typeof BuilderIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderIdRoute: BuilderIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  BuilderRoute: BuilderRouteWithChildren,
  CoverLettersRoute: CoverLettersRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TailoringRoute: TailoringRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
