/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as BuilderIdRouteImport } from './routes/builder.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder': typeof BuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/': typeof BuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/builder' | '/profile' | '/templates' | '/builder/$id' | '/builder/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/templates' | '/builder/$id' | '/builder'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/profile'
    | '/templates'
    | '/builder/$id'
    | '/builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof BuilderRoute
    }
  }
}

interface BuilderRouteChildren {
  BuilderIdRoute: typeof BuilderIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderIdRoute: BuilderIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRouteWithChildren,
  ProfileRoute: ProfileRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
